import rework, perfomance improvements, bash bug fix

diff --git a/bashx b/bashx
--- a/bashx
+++ b/bashx
@@ -8,7 +8,7 @@ function _render() {
 local level=0 flevel=0 inscript=false output='' i=0 tag=''
 local -a parent=() extra=()
 function @error() {
-  [[ ${#FUNCNAME[@]} > 1 ]] && echo -n "(${FUNCNAME[1]}) "
+  [[ ${#FUNCNAME[@]} > 1 ]] && echo -n "(${FUNCNAME[1]}) " >&2
   echo "${_red}Error:${_nc} ${@}" >&2
 }
 while read -r line; do 
@@ -24,7 +24,8 @@ while read -r line; do
       [[ "$line" =~ /\>.* ]] && nextline=$(sed 's|^.*/>\(.*\)|\1|' <<< "$line") && line="${line//$nextline}" 
       line="${line%%\/\>}"
       line="${line%%\>}"
-      output+="${line##\<}"$'\n' # only keep the function and it's arguments
+      line="${line##\<}"
+      output+="$line"$'\n' # only keep the function and it's arguments
     else
       #echo "$line" >&2
       read tag _ <<< "$line"
@@ -60,7 +61,7 @@ done
 #output="$(echo "$output" | sed 's|\(.*\)}|\1|')"
 # <<< "${input}"
 
-echo "$output"
+render_output="$output"
 unset input output level flevel i inscript parent line nextline
 } 
 
@@ -79,10 +80,11 @@ local out2=$(echo "$input" | awk 'function count(s, c) { n=0; for (i=1; i<=lengt
 #return
 while read -d $'\r' block; do
   #echo "${block}"
-  block1=$(echo "${block//$'\n'}" | sed 's|\([a-zA-Z|"|\@|\/]\)>|\1>\n|g; s|\(</[^>]*>\)|\n\1|g') 
+  block1=$(echo "${block//$'\n'}" | sed 's|\([a-zA-Z0-9|"|\@|\/]\)>|\1>\n|g; s|\(</[^>]*>\)|\n\1|g') 
   if [[ "${block//$'\n'}" =~ 'html' ]]; then
     block1="${block1%%\}}"
-    local newblock="{"$'\n'"$(_render "" <<< "${block1/@return html \{}")"$'\n'"}"
+    _render "" <<< "${block1/@return html \{}"
+    local newblock="{"$'\n'"${render_output}"$'\n'"}"
   elif [[ "${block//$'\n'}" =~ "json" ]]; then 
     local newblock="${block/@return json}"
     newblock="${newblock//\};/\}}"
@@ -93,7 +95,7 @@ eof
 )
     newblock="${newblock//  }"
   fi
-  #  echo "$newblock"
+  newblock="${newblock##$'\n'}"
   block="${block//$'\n'/#NEWLIN#}"
   block="${block//\[/\\\[}"
   block="${block//\]/\\\]}"
@@ -194,15 +196,16 @@ function import() {
     else
       fn_name="$1"
     fi
-    eval "${fn_name}() { source \"$name\"; }"
+    eval "${fn_name}() { $(cat "$name") }"
   elif [[ "$1" == "from" ]]; then
     shift
     filename="$1"
     if [ ! -f "$filename" ]; then
-      echo "$name not found to import."
+      error "$name not found to import."
       exit 1
     fi
-    local funcout="$(sed -n '/'"$name"'.*\(\)/,/^}/p' "$filename")"
+    [[ "$filename" =~ .shx|.bashx ]] && local funcout="$(bashx "$filename" && declare -f "$name" && declare -f "/$name")" || local funcout="$(. "$filename" && declare -f "$name")"
+    [ -z "$funcout" ] && error "$name is not found in $filename" && return 1
     shift
     if [[ "$1" == "as" ]]; then
       shift
@@ -213,9 +216,7 @@ function import() {
       fi
       eval "${funcout/$name/$fn_name}"
     else
-      if [[ -n "$funcout" ]]; then 
-        echo "$funcout" | bashx 
-      fi
+      [[ "$funcout" ]] && eval "$funcout"
     fi
   else 
     [[ -n "$name" ]] && { [[ "$name" =~ .shx|.bashx ]] && bashx "$name" || source "$name"; }
@@ -230,8 +231,10 @@ elif [[ -z $BASHX_NESTED ]]; then
   if [ -z "$1" ]; then
     @error "Invalid usage: Use $0 [filename]"
     exit 1
-  elif [ -f "$1" ]; then 
-    bashx "$1"
+  elif [ -f "$1" ]; then
+    filename="$1" 
+    [[ "$filename" != "${filename##*/}" ]] && cd "${filename%/*}" && filename="${filename##*/}"
+    bashx "$filename"
     exit
   else
     @error "$1 is not found"
